// Topic-wise study materials data for all NTA syllabus chapters

type TopicMaterial = {
    concepts: string[];
    formulas: string[];
    solvedExample: { q: string; a: string };
    practiceQs: { q: string; opts: string[]; ans: number }[];
    pyqs: { year: string; q: string; ans: string }[];
    flashcards: { front: string; back: string }[];
};

export const TOPIC_MATERIALS: Record<string, Record<string, TopicMaterial>> = {
    // ═══════════════════════════════════════════════════════════════
    // MATHEMATICS
    // ═══════════════════════════════════════════════════════════════
    Mathematics: {
        'Sets, Relations, and Functions': {
            concepts: ['A set is a well-defined collection of distinct objects', 'Types: finite, infinite, empty, universal', 'Operations: union (∪), intersection (∩), complement, difference', 'Relations: reflexive, symmetric, transitive, equivalence', 'Functions: one-one (injective), onto (surjective), bijective'],
            formulas: ['n(A∪B) = n(A) + n(B) − n(A∩B)', 'n(A∪B∪C) = n(A)+n(B)+n(C)−n(A∩B)−n(B∩C)−n(A∩C)+n(A∩B∩C)', 'De Morgan: (A∪B)′ = A′∩B′', 'Number of relations on set of n elements = 2^(n²)'],
            solvedExample: { q: 'If A = {1,2,3,4} and B = {3,4,5,6}, find A∪B and A∩B.', a: 'A∪B = {1,2,3,4,5,6}, A∩B = {3,4}' },
            practiceQs: [
                { q: 'If n(A) = 20, n(B) = 30, n(A∩B) = 10, find n(A∪B)', opts: ['40', '50', '60', '30'], ans: 0 },
                { q: 'Which relation on {1,2,3} is an equivalence relation?', opts: ['{(1,1),(2,2),(3,3)}', '{(1,2),(2,1)}', '{(1,2)}', '{(1,3)}'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Number of onto functions from {1,2,3,4} to {a,b}?', ans: '14' }],
            flashcards: [{ front: 'What is an equivalence relation?', back: 'A relation that is reflexive, symmetric, and transitive simultaneously' }, { front: 'Bijective function', back: 'A function that is both one-one and onto' }],
        },
        'Complex Numbers and Quadratic Equations': {
            concepts: ['i = √(−1), i² = −1, i³ = −i, i⁴ = 1', 'z = a + ib, conjugate z̄ = a − ib', '|z| = √(a² + b²), arg(z) = tan⁻¹(b/a)', 'Quadratic: ax²+bx+c=0, roots = (−b±√D)/2a where D=b²−4ac', 'Nature of roots: D>0 real distinct, D=0 equal, D<0 complex'],
            formulas: ['Sum of roots α+β = −b/a', 'Product of roots αβ = c/a', '|z₁z₂| = |z₁||z₂|', 'arg(z₁z₂) = arg(z₁) + arg(z₂)', 'Euler: e^(iθ) = cosθ + i sinθ'],
            solvedExample: { q: 'Find the modulus and argument of z = 1+i.', a: '|z| = √2, arg(z) = π/4' },
            practiceQs: [
                { q: 'If z = 3+4i, find |z|', opts: ['5', '7', '1', '25'], ans: 0 },
                { q: 'Roots of x²−5x+6=0 are?', opts: ['2 and 3', '1 and 6', '−2 and −3', '−1 and −6'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Number of real roots of x⁴ − 5x² + 4 = 0', ans: '4 (substitute y=x²)' }],
            flashcards: [{ front: 'What is the discriminant?', back: 'D = b²−4ac. D>0: real roots, D=0: equal roots, D<0: complex roots' }],
        },
        'Matrices and Determinants': {
            concepts: ['Matrix: rectangular array of numbers', 'Types: square, diagonal, identity, symmetric, skew-symmetric', 'Operations: addition, scalar multiplication, matrix multiplication', 'Determinant: scalar value from square matrix', 'Inverse exists iff det(A) ≠ 0'],
            formulas: ['det(AB) = det(A)·det(B)', '(AB)⁻¹ = B⁻¹A⁻¹', 'A·adj(A) = det(A)·I', 'A⁻¹ = adj(A)/det(A)', 'det(kA) = kⁿ det(A) for n×n matrix'],
            solvedExample: { q: 'Find det of [[1,2],[3,4]].', a: 'det = 1×4 − 2×3 = 4−6 = −2' },
            practiceQs: [
                { q: 'If A is 3×3 and det(A)=5, find det(2A)', opts: ['40', '10', '20', '80'], ans: 0 },
                { q: 'A matrix A is singular when?', opts: ['det(A)=0', 'det(A)=1', 'A is symmetric', 'A is diagonal'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2022', q: 'If A² = A, then det(A) = ?', ans: '0 or 1' }],
            flashcards: [{ front: 'Orthogonal matrix', back: 'A matrix where A·Aᵀ = I, i.e., A⁻¹ = Aᵀ' }],
        },
        'Permutations and Combinations': {
            concepts: ['Fundamental counting principle: m×n ways', 'Permutation: arrangement where order matters', 'Combination: selection where order does not matter', 'Circular permutations = (n−1)!', 'Permutations with repetition allowed = nʳ'],
            formulas: ['P(n,r) = n!/(n−r)!', 'C(n,r) = n!/[r!(n−r)!]', 'C(n,r) = C(n,n−r)', 'Total subsets of n elements = 2ⁿ'],
            solvedExample: { q: 'How many 3-letter words from {A,B,C,D,E} without repetition?', a: 'P(5,3) = 5×4×3 = 60' },
            practiceQs: [
                { q: 'C(10,3) = ?', opts: ['120', '720', '210', '60'], ans: 0 },
                { q: 'Number of diagonals of a polygon with 8 sides?', opts: ['20', '28', '16', '24'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Number of ways to distribute 5 identical balls in 3 distinct boxes?', ans: 'C(7,2) = 21' }],
            flashcards: [{ front: 'Derangement formula', back: 'Dₙ = n!(1 − 1/1! + 1/2! − 1/3! + ... + (−1)ⁿ/n!)' }],
        },
        'Binomial Theorem': {
            concepts: ['(a+b)ⁿ = Σ C(n,r) aⁿ⁻ʳ bʳ', 'General term: T(r+1) = C(n,r) aⁿ⁻ʳ bʳ', 'Middle term(s): if n even → 1 middle term; if n odd → 2 middle terms', 'Binomial coefficients are symmetric: C(n,r) = C(n,n−r)'],
            formulas: ['(1+x)ⁿ = Σ C(n,r)xʳ', 'Sum of coefficients: put x=1 → 2ⁿ', 'C(n,0)+C(n,1)+...+C(n,n) = 2ⁿ', 'Greatest coefficient: C(n,n/2) when n is even'],
            solvedExample: { q: 'Find the 4th term of (x+2)⁶.', a: 'T₄ = C(6,3)x³·2³ = 20·8x³ = 160x³' },
            practiceQs: [
                { q: 'Coefficient of x³ in (1+x)⁵?', opts: ['10', '5', '20', '15'], ans: 0 },
                { q: 'Number of terms in (a+b)¹⁰?', opts: ['11', '10', '9', '12'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2022', q: 'Sum of binomial coefficients of (1+x)²⁰?', ans: '2²⁰ = 1048576' }],
            flashcards: [{ front: 'Pascal\'s Rule', back: 'C(n,r) = C(n−1,r−1) + C(n−1,r)' }],
        },
        'Sequence and Series': {
            concepts: ['AP: a, a+d, a+2d, ... | nth term = a+(n−1)d', 'GP: a, ar, ar², ... | nth term = arⁿ⁻¹', 'HP: reciprocals form an AP', 'AM ≥ GM ≥ HM for positive numbers', 'Sum of infinite GP = a/(1−r) when |r|<1'],
            formulas: ['AP sum: Sₙ = n/2[2a+(n−1)d]', 'GP sum: Sₙ = a(rⁿ−1)/(r−1)', 'AM = (a+b)/2', 'GM = √(ab)', 'HM = 2ab/(a+b)'],
            solvedExample: { q: 'Find sum of first 20 terms of AP: 2,5,8,...', a: 'a=2, d=3, S₂₀ = 20/2[4+57] = 10×61 = 610' },
            practiceQs: [
                { q: 'Sum of infinite GP: 1 + 1/2 + 1/4 + ...?', opts: ['2', '1', '3', '∞'], ans: 0 },
                { q: '10th term of AP: 3,7,11,...?', opts: ['39', '43', '35', '47'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'If 3 numbers in GP have product 216, find the middle number', ans: '6' }],
            flashcards: [{ front: 'AM ≥ GM inequality', back: '(a+b)/2 ≥ √(ab) for positive a,b. Equality when a=b.' }],
        },
        'Limit, Continuity, and Differentiability': {
            concepts: ['Limit: lim(x→a) f(x) exists if LHL = RHL', 'Continuity: f is continuous at a if lim f(x) = f(a)', 'Differentiability implies continuity but not vice-versa', 'L\'Hôpital\'s rule for 0/0 or ∞/∞ forms', 'Standard limits: lim(x→0) sinx/x = 1'],
            formulas: ['d/dx(xⁿ) = nxⁿ⁻¹', 'd/dx(sinx) = cosx', 'd/dx(eˣ) = eˣ', 'd/dx(lnx) = 1/x', 'Chain rule: d/dx f(g(x)) = f\'(g(x))·g\'(x)'],
            solvedExample: { q: 'Find lim(x→0) (eˣ−1)/x.', a: 'Using L\'Hôpital: lim = eˣ/1 at x=0 = 1' },
            practiceQs: [
                { q: 'lim(x→0) sin(3x)/x = ?', opts: ['3', '1', '0', '∞'], ans: 0 },
                { q: 'd/dx(x²sinx) = ?', opts: ['2xsinx+x²cosx', 'x²cosx', '2xsinx', '2xcosx'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'lim(x→0) (1−cos2x)/x² = ?', ans: '2' }],
            flashcards: [{ front: 'L\'Hôpital\'s Rule', back: 'If lim f/g = 0/0 or ∞/∞, then lim f/g = lim f\'/g\'' }],
        },
        'Integral Calculus': {
            concepts: ['Indefinite integral: antiderivative + C', 'Definite integral: area under curve from a to b', 'Methods: substitution, by parts, partial fractions', 'Properties of definite integrals: ∫ₐᵇ = −∫ᵇₐ', 'Fundamental theorem connects differentiation and integration'],
            formulas: ['∫xⁿ dx = xⁿ⁺¹/(n+1) + C', '∫eˣ dx = eˣ + C', '∫sinx dx = −cosx + C', '∫dx/x = ln|x| + C', 'By parts: ∫u dv = uv − ∫v du'],
            solvedExample: { q: 'Evaluate ∫₀¹ x·eˣ dx.', a: 'By parts: [xeˣ − eˣ]₀¹ = (e−e)−(0−1) = 1' },
            practiceQs: [
                { q: '∫cos²x dx = ?', opts: ['x/2 + sin2x/4 + C', 'sin²x + C', 'cosx + C', 'x + C'], ans: 0 },
                { q: '∫₀^π sinx dx = ?', opts: ['2', '0', '1', 'π'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2022', q: '∫₀¹ x²eˣ dx = ?', ans: 'e − 2' }],
            flashcards: [{ front: 'ILATE rule', back: 'Integration by parts priority: Inverse trig, Log, Algebraic, Trig, Exponential' }],
        },
        'Differential Equations': {
            concepts: ['Order: highest derivative order; Degree: power of highest order derivative', 'Variable separable: dy/dx = f(x)g(y)', 'Homogeneous: dy/dx = f(y/x)', 'Linear: dy/dx + Py = Q, IF = e^(∫P dx)', 'General and particular solutions'],
            formulas: ['Variable separable: ∫dy/g(y) = ∫f(x)dx', 'Linear DE solution: y·IF = ∫Q·IF dx', 'IF = e^(∫P dx)', 'Homogeneous: put y = vx'],
            solvedExample: { q: 'Solve dy/dx = x/y.', a: 'y dy = x dx → y²/2 = x²/2 + C → x² − y² = C' },
            practiceQs: [
                { q: 'Order and degree of d²y/dx² + (dy/dx)³ = 0?', opts: ['Order 2, Degree 1', 'Order 3, Degree 2', 'Order 2, Degree 3', 'Order 1, Degree 2'], ans: 0 },
                { q: 'IF of dy/dx + 2y = eˣ?', opts: ['e²ˣ', 'eˣ', 'e⁻²ˣ', '2x'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Solution of dy/dx = y/x passing through (1,1)?', ans: 'y = x' }],
            flashcards: [{ front: 'Integrating Factor (IF)', back: 'For dy/dx + Py = Q: IF = e^(∫P dx). Multiply both sides by IF to make LHS exact.' }],
        },
        'Coordinate Geometry': {
            concepts: ['Distance = √[(x₂−x₁)²+(y₂−y₁)²]', 'Section formula: internal division (mx₂+nx₁)/(m+n)', 'Straight line: y−y₁ = m(x−x₁)', 'Circle: (x−h)²+(y−k)² = r²', 'Conic sections: parabola y²=4ax, ellipse x²/a²+y²/b²=1, hyperbola x²/a²−y²/b²=1'],
            formulas: ['Slope m = (y₂−y₁)/(x₂−x₁)', 'General line: ax+by+c=0', 'Distance from point to line = |ax₁+by₁+c|/√(a²+b²)', 'Eccentricity: e<1 ellipse, e=1 parabola, e>1 hyperbola'],
            solvedExample: { q: 'Find equation of circle with center (1,2) and radius 3.', a: '(x−1)²+(y−2)² = 9' },
            practiceQs: [
                { q: 'Slope of line joining (1,2) and (3,8)?', opts: ['3', '2', '4', '1'], ans: 0 },
                { q: 'Focus of parabola y²=12x?', opts: ['(3,0)', '(0,3)', '(12,0)', '(6,0)'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2022', q: 'Eccentricity of x²/9+y²/4=1?', ans: '√5/3' }],
            flashcards: [{ front: 'Condition for perpendicular lines', back: 'm₁ × m₂ = −1' }],
        },
        'Three-Dimensional Geometry': {
            concepts: ['Distance in 3D: √[(x₂−x₁)²+(y₂−y₁)²+(z₂−z₁)²]', 'Direction cosines: l²+m²+n² = 1', 'Equation of line: (x−x₁)/a = (y−y₁)/b = (z−z₁)/c', 'Equation of plane: ax+by+cz+d = 0', 'Angle between two planes via normals'],
            formulas: ['Distance from point to plane = |ax₁+by₁+cz₁+d|/√(a²+b²+c²)', 'Angle between planes: cosθ = |n₁·n₂|/(|n₁||n₂|)', 'Skew lines shortest distance = |(a₂−a₁)·(b₁×b₂)|/|b₁×b₂|'],
            solvedExample: { q: 'Find distance of point (1,2,3) from plane x+2y+2z=9.', a: '|1+4+6−9|/√(1+4+4) = 2/3' },
            practiceQs: [
                { q: 'Direction ratios of line joining (1,0,0) and (0,1,1)?', opts: ['−1,1,1', '1,1,1', '1,0,1', '0,1,0'], ans: 0 },
                { q: 'Angle between planes x+y=0 and y+z=0?', opts: ['60°', '90°', '45°', '30°'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Foot of perpendicular from origin to plane 2x+3y+6z=14?', ans: '(4/7, 6/7, 12/7)' }],
            flashcards: [{ front: 'Condition for coplanar lines', back: 'The scalar triple product of direction vectors and connecting vector = 0' }],
        },
        'Vector Algebra': {
            concepts: ['Vector = magnitude + direction', 'Dot product: a·b = |a||b|cosθ (scalar)', 'Cross product: a×b = |a||b|sinθ n̂ (vector)', 'Unit vector: â = a/|a|', 'Scalar triple product: a·(b×c) = volume of parallelepiped'],
            formulas: ['|a+b|² = |a|²+|b|²+2a·b', 'a×b = −b×a', 'a·(b×c) = [a b c]', 'Area of triangle = ½|a×b|', 'Area of parallelogram = |a×b|'],
            solvedExample: { q: 'Find |a×b| if |a|=3, |b|=4, θ=30°.', a: '|a×b| = 3×4×sin30° = 6' },
            practiceQs: [
                { q: 'a·b = 0 implies?', opts: ['Perpendicular', 'Parallel', 'Equal', 'Zero vectors'], ans: 0 },
                { q: 'If a = 2i+3j+k, find |a|', opts: ['√14', '√6', '6', '14'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2022', q: 'If a×b = 0 and a·b = 0, then?', ans: 'At least one is zero vector' }],
            flashcards: [{ front: 'When is a×b = 0?', back: 'When vectors are parallel (θ=0° or 180°) or one is zero vector' }],
        },
        'Statistics and Probability': {
            concepts: ['Mean, median, mode — measures of central tendency', 'Variance = Σ(xᵢ−x̄)²/n, SD = √Variance', 'P(A) = favorable/total outcomes', 'P(A∪B) = P(A)+P(B)−P(A∩B)', 'Bayes theorem: P(A|B) = P(B|A)P(A)/P(B)'],
            formulas: ['Var(X) = E(X²)−[E(X)]²', 'Binomial: P(X=k) = C(n,k)pᵏ(1−p)ⁿ⁻ᵏ', 'Conditional: P(A|B) = P(A∩B)/P(B)', 'Var(aX+b) = a²Var(X)'],
            solvedExample: { q: 'Find mean and variance of {2,4,6,8,10}.', a: 'Mean = 6, Variance = (16+4+0+4+16)/5 = 8' },
            practiceQs: [
                { q: 'If variance of x is 5, variance of 2x+3?', opts: ['20', '10', '23', '13'], ans: 0 },
                { q: 'P(A)=0.6, P(B)=0.4, P(A∩B)=0.2, find P(A∪B)', opts: ['0.8', '1.0', '0.6', '0.4'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'Mean of binomial distribution B(10,0.3)?', ans: '3' }],
            flashcards: [{ front: 'Total probability theorem', back: 'P(A) = ΣP(A|Bᵢ)P(Bᵢ) where Bᵢ are exhaustive & mutually exclusive' }],
        },
        'Trigonometry': {
            concepts: ['sin²θ+cos²θ = 1', 'tan θ = sinθ/cosθ', 'sin(A±B) = sinAcosB ± cosAsinB', 'cos(A±B) = cosAcosB ∓ sinAsinB', 'General solutions of trig equations'],
            formulas: ['sin2A = 2sinAcosA', 'cos2A = cos²A−sin²A', '1+tan²A = sec²A', '1+cot²A = csc²A', 'Period of sinx, cosx = 2π; tanx = π'],
            solvedExample: { q: 'Solve sinx = 1/2 for general solution.', a: 'x = nπ + (−1)ⁿ(π/6), n ∈ ℤ' },
            practiceQs: [
                { q: 'sin(90°−θ) = ?', opts: ['cosθ', 'sinθ', 'tanθ', '−cosθ'], ans: 0 },
                { q: 'Period of sin2x?', opts: ['π', '2π', 'π/2', '4π'], ans: 0 },
            ],
            pyqs: [{ year: 'JEE 2023', q: 'General solution of cos2x = 0?', ans: 'x = (2n+1)π/4' }],
            flashcards: [{ front: 'Range of sinx', back: '[−1, 1]' }, { front: 'sin(90°−θ) = ?', back: 'cosθ' }],
        },
    },
    // ═══════════════════════════════════════════════════════════════
    // PHYSICS
    // ═══════════════════════════════════════════════════════════════
    Physics: {
        'Physics and Measurement': {
            concepts: ['SI units: 7 base units (m, kg, s, A, K, mol, cd)', 'Dimensional analysis to check equations', 'Significant figures and rounding rules', 'Errors: systematic vs random, absolute vs relative', 'Least count of instruments'],
            formulas: ['Relative error = Δa/a', 'Percentage error = (Δa/a)×100', 'Dimensions: [MLT] system', 'If Z=AⁿBᵐ, ΔZ/Z = nΔA/A + mΔB/B'],
            solvedExample: { q: 'Check dimensional consistency of v = u + at.', a: '[LT⁻¹] = [LT⁻¹] + [LT⁻²][T] = [LT⁻¹] ✓ Consistent' },
            practiceQs: [{ q: 'Dimension of Planck constant h?', opts: ['ML²T⁻¹', 'MLT⁻²', 'ML²T⁻²', 'MLT⁻¹'], ans: 0 }, { q: 'Number of significant figures in 0.00620?', opts: ['3', '5', '2', '4'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Dimensions of permittivity ε₀?', ans: 'M⁻¹L⁻³T⁴A²' }],
            flashcards: [{ front: 'Dimensionless quantities', back: 'Angle (radian), strain, refractive index, relative density' }],
        },
        'Kinematics': {
            concepts: ['Distance vs displacement', 'Speed vs velocity', 'Uniform and non-uniform acceleration', 'Projectile motion: parabolic path', 'Relative velocity'],
            formulas: ['v = u + at', 's = ut + ½at²', 'v² = u² + 2as', 'Range R = u²sin2θ/g', 'Max height H = u²sin²θ/2g'],
            solvedExample: { q: 'A ball is thrown at 20 m/s at 30°. Find range.', a: 'R = 20²×sin60°/10 = 400×0.866/10 = 34.64 m' },
            practiceQs: [{ q: 'Time of flight for 45° projectile at 40m/s?', opts: ['4√2 s', '4 s', '2√2 s', '8 s'], ans: 0 }, { q: 'Acceleration due to gravity on moon is g/6. A body dropped from 30m takes?', opts: ['6 s', '3 s', '√36 s', '√60 s'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Two projectiles have same range. If angles are θ and 90°−θ, ratio of max heights?', ans: 'tan²θ' }],
            flashcards: [{ front: 'Projectile at 45°', back: 'Maximum range R = u²/g. Time of flight = √2·u/g' }],
        },
        'Laws of Motion': {
            concepts: ['Newton\'s 1st law: inertia', 'Newton\'s 2nd law: F = ma', 'Newton\'s 3rd law: action-reaction pairs', 'Free body diagrams', 'Friction: static (μₛmg) and kinetic (μₖmg)'],
            formulas: ['F = ma', 'Friction f ≤ μN', 'Momentum p = mv', 'Impulse J = FΔt = Δp', 'For connected bodies: a = F_net/m_total'],
            solvedExample: { q: 'A 5 kg block on a surface with μ=0.3. Find friction if F=10N horizontal.', a: 'Max friction = 0.3×5×10 = 15N > 10N, so f = 10N (block static)' },
            practiceQs: [{ q: 'A lift accelerates up at 2 m/s². Apparent weight of 50 kg person?', opts: ['600 N', '500 N', '400 N', '700 N'], ans: 0 }, { q: 'Which law explains rocket propulsion?', opts: ['3rd law', '1st law', '2nd law', 'Gravitation'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Two blocks (2kg, 3kg) connected by string on frictionless surface. Force 10N on 3kg block. Tension?', ans: '4N' }],
            flashcards: [{ front: 'Pseudo force', back: 'F = −ma₀ applied in non-inertial frame, opposite to frame acceleration a₀' }],
        },
        'Work, Energy, and Power': {
            concepts: ['Work W = F·d·cosθ', 'KE = ½mv²', 'PE = mgh (gravitational)', 'Work-energy theorem: W_net = ΔKE', 'Conservation of mechanical energy in conservative forces'],
            formulas: ['W = Fd cosθ', 'KE = ½mv²', 'P = W/t = Fv', 'Spring PE = ½kx²', 'Elastic collision: KE conserved'],
            solvedExample: { q: 'A 2 kg ball falls from 10m. Find KE just before hitting ground.', a: 'KE = mgh = 2×10×10 = 200 J' },
            practiceQs: [{ q: 'Power of engine moving car at 20 m/s against 500N resistance?', opts: ['10 kW', '25 kW', '5 kW', '1 kW'], ans: 0 }, { q: 'Work done by gravity on horizontal displacement?', opts: ['Zero', 'mgh', 'mg', 'Negative'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Coefficient of restitution for perfectly inelastic collision?', ans: '0' }],
            flashcards: [{ front: 'Conservative force', back: 'Work done is path-independent. Examples: gravity, spring force, electrostatic' }],
        },
        'Rotational Motion': {
            concepts: ['Moment of inertia I = Σmr²', 'Torque τ = r × F', 'Angular momentum L = Iω', 'Rolling motion: v = Rω', 'Parallel and perpendicular axis theorems'],
            formulas: ['τ = Iα', 'L = Iω', 'KE_rot = ½Iω²', 'I_parallel = I_cm + Md²', 'I_perp = Ix + Iy (thin lamina)'],
            solvedExample: { q: 'MOI of solid sphere about diameter?', a: 'I = (2/5)MR²' },
            practiceQs: [{ q: 'MOI of ring about diameter?', opts: ['MR²/2', 'MR²', '2MR²', 'MR²/4'], ans: 0 }, { q: 'A disc rolls without slipping. Ratio of rotational to translational KE?', opts: ['1:2', '1:1', '2:1', '1:3'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Angular momentum is conserved when?', ans: 'Net external torque is zero' }],
            flashcards: [{ front: 'Rolling without slipping', back: 'v_cm = Rω, friction provides torque but does no work' }],
        },
        'Gravitation': {
            concepts: ['Newton\'s law: F = GMm/r²', 'g at surface: g = GM/R²', 'Variation of g with height and depth', 'Orbital velocity and escape velocity', 'Kepler\'s laws of planetary motion'],
            formulas: ['F = GMm/r²', 'g = GM/R²', 'v_orbital = √(GM/r)', 'v_escape = √(2GM/R) = √(2gR)', 'T² ∝ r³ (Kepler 3rd)'],
            solvedExample: { q: 'Find escape velocity from Earth (R=6400km, g=10m/s²).', a: 'v = √(2×10×6.4×10⁶) = √(1.28×10⁸) ≈ 11.3 km/s' },
            practiceQs: [{ q: 'Ratio of orbital to escape velocity?', opts: ['1:√2', '√2:1', '1:2', '2:1'], ans: 0 }, { q: 'At what height is g reduced to half?', opts: ['(√2−1)R', 'R/2', 'R', '2R'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Gravitational PE at infinity is?', ans: 'Zero (by convention)' }],
            flashcards: [{ front: 'Kepler\'s 3rd law', back: 'T² ∝ a³ — square of period proportional to cube of semi-major axis' }],
        },
        'Properties of Solids and Liquids': {
            concepts: ['Stress = Force/Area, Strain = ΔL/L', 'Young\'s modulus Y = stress/strain', 'Surface tension and capillarity', 'Viscosity and Stokes\' law', 'Bernoulli\'s principle for fluid flow'],
            formulas: ['Y = FL/(AΔL)', 'Pressure P = ρgh', 'Bernoulli: P + ½ρv² + ρgh = const', 'Stokes: F = 6πηrv', 'Surface tension T = F/L'],
            solvedExample: { q: 'A wire of L=2m, A=1mm², stretches 1mm under 100N. Find Y.', a: 'Y = FL/(AΔL) = 100×2/(10⁻⁶×10⁻³) = 2×10¹¹ Pa' },
            practiceQs: [{ q: 'Water rises in capillary tube due to?', opts: ['Surface tension', 'Viscosity', 'Gravity', 'Pressure'], ans: 0 }, { q: 'Unit of viscosity?', opts: ['Pa·s', 'N/m', 'Pa', 'N·s/m'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Terminal velocity of sphere is proportional to?', ans: 'r² (radius squared)' }],
            flashcards: [{ front: 'Bernoulli\'s principle', back: 'In streamline flow: P + ½ρv² + ρgh = constant along a streamline' }],
        },
        'Thermodynamics': {
            concepts: ['First law: ΔU = Q − W', 'Isothermal: T constant, PV = const', 'Adiabatic: Q = 0, PVᵞ = const', 'Entropy always increases in isolated systems', 'Carnot efficiency = 1 − T₂/T₁'],
            formulas: ['ΔU = nCᵥΔT', 'W = PΔV (isobaric)', 'W = nRT ln(V₂/V₁) (isothermal)', 'Cₚ − Cᵥ = R', 'γ = Cₚ/Cᵥ'],
            solvedExample: { q: 'Carnot engine between 500K and 300K. Find efficiency.', a: 'η = 1 − 300/500 = 0.4 = 40%' },
            practiceQs: [{ q: 'Work done in free expansion?', opts: ['Zero', 'Positive', 'Negative', 'PΔV'], ans: 0 }, { q: 'In adiabatic process?', opts: ['Q = 0', 'W = 0', 'ΔU = 0', 'ΔT = 0'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'Entropy change of universe in irreversible process?', ans: 'Always positive' }],
            flashcards: [{ front: 'Second Law', back: 'Heat cannot spontaneously flow from cold to hot body' }],
        },
        'Kinetic Theory of Gases': {
            concepts: ['Ideal gas: PV = nRT', 'KE per molecule = (3/2)kT', 'RMS speed = √(3RT/M)', 'Degrees of freedom: mono=3, di=5, poly=6', 'Mean free path'],
            formulas: ['PV = nRT', 'KE = (3/2)nRT', 'v_rms = √(3RT/M)', 'v_avg = √(8RT/πM)', 'v_mp = √(2RT/M)'],
            solvedExample: { q: 'RMS speed of O₂ at 300K (M=32g/mol)?', a: 'v = √(3×8.314×300/0.032) ≈ 483 m/s' },
            practiceQs: [{ q: 'Ratio v_rms : v_avg : v_mp?', opts: ['√3:√(8/π):√2', '3:2:1', '1:1:1', '√2:√3:1'], ans: 0 }, { q: 'DOF of diatomic at room temp?', opts: ['5', '3', '6', '7'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'At what temperature does RMS speed of H₂ equal that of O₂ at 300K?', ans: '300/16 = 18.75 K' }],
            flashcards: [{ front: 'Equipartition theorem', back: 'Each DOF contributes ½kT to avg energy per molecule' }],
        },
        'Oscillations and Waves': {
            concepts: ['SHM: a = −ω²x', 'Time period of spring: T = 2π√(m/k)', 'Simple pendulum: T = 2π√(L/g)', 'Wave equation: v = fλ', 'Standing waves, beats, Doppler effect'],
            formulas: ['x = A sin(ωt + φ)', 'ω = 2π/T = 2πf', 'v_wave = √(T/μ) for string', 'Beat freq = |f₁−f₂|', 'Doppler: f\' = f(v±v₀)/(v∓vₛ)'],
            solvedExample: { q: 'Spring constant k=100 N/m, mass=1 kg. Find period.', a: 'T = 2π√(1/100) = 2π/10 = 0.628 s' },
            practiceQs: [{ q: 'In SHM, KE is maximum at?', opts: ['Mean position', 'Extreme position', 'Midway', 'Quarter point'], ans: 0 }, { q: 'Speed of sound in air at 20°C ≈?', opts: ['343 m/s', '300 m/s', '400 m/s', '250 m/s'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Two tuning forks give 4 beats/s. One is 256 Hz. Other?', ans: '252 or 260 Hz' }],
            flashcards: [{ front: 'Resonance', back: 'When driving frequency = natural frequency, amplitude is maximum' }],
        },
        'Electrostatics': {
            concepts: ['Coulomb\'s law: F = kq₁q₂/r²', 'Electric field E = F/q', 'Gauss\'s law: ΦE = q_enc/ε₀', 'Electric potential V = kq/r', 'Capacitance C = Q/V'],
            formulas: ['F = kq₁q₂/r²', 'E = kq/r²', 'V = kq/r', 'C_parallel plate = ε₀A/d', 'Energy = ½CV² = Q²/2C'],
            solvedExample: { q: 'Force between 2μC and 3μC charges 30cm apart?', a: 'F = 9×10⁹×2×10⁻⁶×3×10⁻⁶/0.09 = 0.6 N' },
            practiceQs: [{ q: 'Electric field inside conductor?', opts: ['Zero', 'Maximum', 'Constant', 'Variable'], ans: 0 }, { q: 'Capacitors in series: total C?', opts: ['1/C = 1/C₁+1/C₂', 'C = C₁+C₂', 'C = C₁C₂', 'C = C₁−C₂'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Electric flux through closed surface enclosing charge Q?', ans: 'Q/ε₀' }],
            flashcards: [{ front: 'Equipotential surface', back: 'Surface where V is constant. E is perpendicular to it. No work to move charge along it.' }],
        },
        'Current Electricity': {
            concepts: ['Ohm\'s law: V = IR', 'Resistivity ρ = RA/L', 'Kirchhoff\'s laws: junction (ΣI=0) and loop (ΣV=0)', 'Wheatstone bridge', 'Meter bridge and potentiometer'],
            formulas: ['R = ρL/A', 'Series: R = R₁+R₂', 'Parallel: 1/R = 1/R₁+1/R₂', 'Power P = VI = I²R = V²/R', 'EMF = V + Ir'],
            solvedExample: { q: '3Ω and 6Ω in parallel. Find equivalent R.', a: '1/R = 1/3+1/6 = 1/2, R = 2Ω' },
            practiceQs: [{ q: 'Wheatstone bridge balance condition?', opts: ['P/Q = R/S', 'PQ = RS', 'P+Q = R+S', 'P−Q = R−S'], ans: 0 }, { q: 'Internal resistance causes?', opts: ['Terminal voltage < EMF', 'V > EMF', 'No current', 'Infinite current'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Potentiometer is preferred over voltmeter because?', ans: 'It draws no current (null method)' }],
            flashcards: [{ front: 'Kirchhoff\'s Junction Rule', back: 'Sum of currents entering a junction = sum leaving (conservation of charge)' }],
        },
        'Magnetic Effects of Current and Magnetism': {
            concepts: ['Biot-Savart law: dB = μ₀I dl×r̂/4πr²', 'Ampere\'s circuital law', 'Force on current: F = IL×B', 'Lorentz force: F = q(v×B)', 'Magnetic properties: dia, para, ferromagnetic'],
            formulas: ['B (long wire) = μ₀I/2πr', 'B (solenoid) = μ₀nI', 'F = qvBsinθ', 'Torque on loop τ = NIAB sinθ', 'Cyclotron radius r = mv/qB'],
            solvedExample: { q: 'B at center of circular loop radius 10cm carrying 2A?', a: 'B = μ₀I/2R = 4π×10⁻⁷×2/(2×0.1) = 4π×10⁻⁶ T' },
            practiceQs: [{ q: 'Force between two parallel currents in same direction?', opts: ['Attractive', 'Repulsive', 'Zero', 'Perpendicular'], ans: 0 }, { q: 'Magnetic field inside a solenoid is?', opts: ['Uniform', 'Zero', 'Radial', 'Inversely proportional to r'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Cyclotron frequency depends on?', ans: 'q/m ratio and B only (not velocity)' }],
            flashcards: [{ front: 'Right hand rule', back: 'Curl fingers in direction of current; thumb points in direction of magnetic field' }],
        },
        'Electromagnetic Induction and AC': {
            concepts: ['Faraday\'s law: EMF = −dΦ/dt', 'Lenz\'s law: induced current opposes change', 'Self-inductance L, mutual inductance M', 'AC: V = V₀sinωt', 'LCR circuit and resonance'],
            formulas: ['EMF = −N dΦ/dt', 'L = NΦ/I', 'V_rms = V₀/√2', 'Impedance Z = √(R²+(XL−XC)²)', 'Resonance: XL = XC, f = 1/2π√(LC)'],
            solvedExample: { q: 'Self-inductance of solenoid: 500 turns, 20cm, area 10cm².', a: 'L = μ₀N²A/l = 4π×10⁻⁷×250000×10⁻³/0.2 ≈ 1.57 mH' },
            practiceQs: [{ q: 'In LCR series resonance, impedance equals?', opts: ['R', 'XL', 'XC', 'Zero'], ans: 0 }, { q: 'Transformer works on principle of?', opts: ['Mutual induction', 'Self induction', 'Ohm\'s law', 'Ampere\'s law'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Quality factor Q of LCR circuit?', ans: 'ωL/R or 1/ωCR' }],
            flashcards: [{ front: 'Lenz\'s Law', back: 'Induced current opposes the change in magnetic flux that caused it' }],
        },
        'Electromagnetic Waves': {
            concepts: ['EM waves: E and B perpendicular, transverse', 'Speed c = 1/√(μ₀ε₀) = 3×10⁸ m/s', 'EM spectrum: radio → micro → IR → visible → UV → X-ray → gamma', 'Displacement current: Id = ε₀ dΦE/dt', 'Energy transport: Poynting vector S = E×B/μ₀'],
            formulas: ['c = fλ', 'c = E₀/B₀', 'Energy density u = ε₀E²/2 + B²/2μ₀', 'Intensity I = ½ε₀cE₀²'],
            solvedExample: { q: 'Wavelength of EM wave with f = 6×10¹⁴ Hz?', a: 'λ = c/f = 3×10⁸/6×10¹⁴ = 5×10⁻⁷ m = 500 nm (green)' },
            practiceQs: [{ q: 'Which EM wave has shortest wavelength?', opts: ['Gamma rays', 'X-rays', 'UV', 'Radio'], ans: 0 }, { q: 'EM waves are?', opts: ['Transverse', 'Longitudinal', 'Both', 'Neither'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Maxwell\'s displacement current is associated with?', ans: 'Changing electric field between capacitor plates' }],
            flashcards: [{ front: 'Visible light range', back: '400 nm (violet) to 700 nm (red)' }],
        },
        'Optics': {
            concepts: ['Snell\'s law: n₁sinθ₁ = n₂sinθ₂', 'Mirror formula: 1/f = 1/v + 1/u', 'Lens formula: 1/f = 1/v − 1/u', 'Total internal reflection', 'Young\'s double slit interference'],
            formulas: ['Mirror: 1/f = 1/v + 1/u', 'Lens: 1/v − 1/u = 1/f', 'Magnification m = −v/u (mirror)', 'Fringe width β = λD/d', 'Brewster angle: tanθ_B = n'],
            solvedExample: { q: 'Object at 30cm from concave mirror f=20cm. Find image.', a: '1/v = 1/f−1/u = 1/20−1/30 = 1/60, v = 60cm (real)' },
            practiceQs: [{ q: 'Critical angle for glass (n=1.5)?', opts: ['sin⁻¹(2/3)', 'sin⁻¹(3/2)', '45°', '30°'], ans: 0 }, { q: 'In Young\'s experiment, if slit separation halved?', opts: ['Fringe width doubles', 'Halves', 'Same', 'Zero'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Power of lens in diopters if f=25cm?', ans: '+4 D' }],
            flashcards: [{ front: 'Constructive interference', back: 'Path difference = nλ (n=0,1,2...). Waves add up to maximum amplitude' }],
        },
        'Dual Nature of Matter and Radiation': {
            concepts: ['Photoelectric effect: E = hf − φ', 'de Broglie wavelength: λ = h/p = h/mv', 'Wave-particle duality', 'Threshold frequency: f₀ = φ/h', 'Stopping potential: eV₀ = hf − φ'],
            formulas: ['E = hf = hc/λ', 'λ = h/mv', 'KE_max = hf − φ = eV₀', 'h = 6.63×10⁻³⁴ J·s', 'λ = 1.226/√V nm (for electron)'],
            solvedExample: { q: 'de Broglie wavelength of electron accelerated through 100V?', a: 'λ = 1.226/√100 = 0.1226 nm' },
            practiceQs: [{ q: 'Photoelectric effect proves light is?', opts: ['Particle', 'Wave', 'Both', 'Neither'], ans: 0 }, { q: 'If frequency doubled, KE of photoelectron?', opts: ['More than doubles', 'Doubles', 'Halves', 'Same'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Work function of metal is 2eV. Threshold wavelength?', ans: '620 nm' }],
            flashcards: [{ front: 'Work function (φ)', back: 'Minimum energy needed to eject electron from metal surface' }],
        },
        'Atoms and Nuclei': {
            concepts: ['Bohr model: E = −13.6/n² eV', 'Radius rₙ = n²a₀ (a₀ = 0.529 Å)', 'Nuclear binding energy', 'Radioactive decay: N = N₀e⁻λt', 'Fission and fusion'],
            formulas: ['E = −13.6Z²/n² eV', 'r = 0.529n²/Z Å', 'Half-life t½ = ln2/λ', 'BE/A curve: max at Fe-56', 'Q = Δmc²'],
            solvedExample: { q: 'Energy of H-atom electron in n=3 orbit?', a: 'E = −13.6/9 = −1.51 eV' },
            practiceQs: [{ q: 'Half-life of substance is 10 min. After 30 min, fraction remaining?', opts: ['1/8', '1/4', '1/16', '1/2'], ans: 0 }, { q: 'Which has highest BE/A?', opts: ['Fe-56', 'H-1', 'U-238', 'He-4'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'Ratio of radii of 1st and 3rd Bohr orbits?', ans: '1:9' }],
            flashcards: [{ front: 'Mass defect', back: 'Δm = (Zm_p + Nm_n) − M_nucleus. Energy equivalent is binding energy.' }],
        },
        'Electronic Devices': {
            concepts: ['p-n junction diode: forward & reverse bias', 'Zener diode: voltage regulator', 'Transistor: npn and pnp, amplification', 'Logic gates: AND, OR, NOT, NAND, NOR', 'Photodiode, LED, solar cell'],
            formulas: ['Current gain β = Ic/Ib', 'α = Ic/Ie, β = α/(1−α)', 'Zener voltage = constant in breakdown', 'Diode equation: I = I₀(e^(V/nVT)−1)'],
            solvedExample: { q: 'Transistor has β=100, Ib=10μA. Find Ic.', a: 'Ic = βIb = 100×10×10⁻⁶ = 1 mA' },
            practiceQs: [{ q: 'NAND gate is universal because?', opts: ['Can make all gates', 'Fastest', 'Cheapest', 'Smallest'], ans: 0 }, { q: 'In forward bias of p-n junction?', opts: ['Depletion width decreases', 'Increases', 'Unchanged', 'Infinite'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Truth table with output 1 only when both inputs are 1?', ans: 'AND gate' }],
            flashcards: [{ front: 'Depletion region', back: 'Region at p-n junction devoid of free charges. Acts as barrier to current flow.' }],
        },
        'Experimental Skills': {
            concepts: ['Vernier calipers: LC = 1MSD − 1VSD', 'Screw gauge: LC = pitch/divisions', 'Meter bridge for unknown resistance', 'Potentiometer for EMF comparison', 'Focal length using u-v method'],
            formulas: ['Vernier LC = 1/n cm typically 0.01cm', 'Screw gauge LC = 0.5mm/50 = 0.01mm', 'Meter bridge: R = S×l/(100−l)', 'Potentiometer: E₁/E₂ = l₁/l₂'],
            solvedExample: { q: 'Meter bridge: null at 40cm with S=6Ω. Find R.', a: 'R = S×l/(100−l) = 6×40/60 = 4Ω' },
            practiceQs: [{ q: 'Least count of vernier with 10 VSD = 9 MSD, 1MSD=1mm?', opts: ['0.1 mm', '0.01 mm', '1 mm', '0.5 mm'], ans: 0 }, { q: 'Potentiometer measures?', opts: ['EMF accurately', 'Current', 'Resistance', 'Power'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Zero error of screw gauge: thimble reads 3 when closed. LC=0.01mm. Correction?', ans: '−0.03 mm' }],
            flashcards: [{ front: 'Null method advantage', back: 'No current drawn from source → no internal resistance error → more accurate measurement' }],
        },
    },
    // ═══════════════════════════════════════════════════════════════
    // CHEMISTRY
    // ═══════════════════════════════════════════════════════════════
    Chemistry: {
        'Some Basic Concepts in Chemistry': {
            concepts: ['Mole concept: 1 mol = 6.022×10²³ particles', 'Molar mass = mass of 1 mole in grams', 'Molarity M = moles of solute / L of solution', 'Empirical vs molecular formula', 'Limiting reagent determines product amount'],
            formulas: ['n = m/M', 'Molarity = n/V(L)', 'Molality = n/w(kg)', '% yield = (actual/theoretical)×100'],
            solvedExample: { q: 'Moles of NaOH in 200mL of 0.5M solution?', a: 'n = M×V = 0.5×0.2 = 0.1 mol' },
            practiceQs: [{ q: 'Molar mass of H₂SO₄?', opts: ['98 g/mol', '96 g/mol', '100 g/mol', '64 g/mol'], ans: 0 }, { q: 'Number of atoms in 1 mole of O₂?', opts: ['12.044×10²³', '6.022×10²³', '3.011×10²³', '18.066×10²³'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Equivalent weight of H₃PO₄ in reaction forming Na₃PO₄?', ans: '98/3 = 32.67' }],
            flashcards: [{ front: 'Avogadro\'s number', back: '6.022×10²³ — number of particles per mole' }],
        },
        'Atomic Structure': {
            concepts: ['Bohr model for hydrogen-like atoms', 'Quantum numbers: n, l, ml, ms', 'Aufbau principle, Hund\'s rule, Pauli exclusion', 'Shapes of orbitals: s(sphere), p(dumbbell), d(clover)', 'Photoelectric effect and line spectra'],
            formulas: ['E = -13.6Z²/n² eV', 'de Broglie: λ = h/mv', 'Heisenberg: Δx·Δp ≥ h/4π', 'Max electrons in shell = 2n²'],
            solvedExample: { q: 'Electronic configuration of Fe (Z=26)?', a: '[Ar] 3d⁶ 4s²' },
            practiceQs: [{ q: 'Maximum electrons in n=3 shell?', opts: ['18', '8', '32', '2'], ans: 0 }, { q: 'Shape of 3d orbital?', opts: ['Clover/double dumbbell', 'Sphere', 'Dumbbell', 'Ring'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Quantum numbers for 3p electron?', ans: 'n=3, l=1, ml=−1,0,+1, ms=±½' }],
            flashcards: [{ front: 'Hund\'s rule', back: 'Each orbital in a subshell gets one electron before any gets a second (maximize spin)' }],
        },
        'Chemical Bonding and Molecular Structure': {
            concepts: ['Ionic bond: electron transfer', 'Covalent bond: electron sharing', 'VSEPR theory for molecular geometry', 'Hybridization: sp, sp², sp³, sp³d, sp³d²', 'Molecular orbital theory'],
            formulas: ['Bond order = (Nb−Na)/2', 'Formal charge = V−L−B/2', 'Dipole moment μ = q×d'],
            solvedExample: { q: 'Hybridization of carbon in CH₄?', a: 'sp³ — 4 bond pairs, tetrahedral, 109.5°' },
            practiceQs: [{ q: 'Shape of SF₆?', opts: ['Octahedral', 'Tetrahedral', 'Square planar', 'Trigonal'], ans: 0 }, { q: 'Bond order of O₂?', opts: ['2', '1', '3', '1.5'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Hybridization of Xe in XeF₄?', ans: 'sp³d² (square planar)' }],
            flashcards: [{ front: 'Paramagnetism', back: 'Due to unpaired electrons. O₂ is paramagnetic (bond order 2, 2 unpaired e⁻)' }],
        },
        'Chemical Thermodynamics': {
            concepts: ['First law: ΔU = q + w', 'Enthalpy H = U + PV', 'Hess\'s law: ΔH is path independent', 'Spontaneity: ΔG = ΔH − TΔS', 'Standard enthalpy of formation'],
            formulas: ['ΔG = ΔH − TΔS', 'w = −PΔV (expansion work)', 'Cp − Cv = R (ideal gas)', 'ΔH = ΔU + ΔnRT'],
            solvedExample: { q: 'ΔH = −100 kJ, ΔS = −200 J/K at 300K. Is reaction spontaneous?', a: 'ΔG = −100000 − 300(−200) = −100000+60000 = −40000 J = −40 kJ. Yes, spontaneous.' },
            practiceQs: [{ q: 'Exothermic reaction has?', opts: ['ΔH < 0', 'ΔH > 0', 'ΔS > 0', 'ΔG > 0'], ans: 0 }, { q: 'At equilibrium, ΔG = ?', opts: ['0', 'Negative', 'Positive', 'ΔH'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'ΔH_f° of an element in standard state?', ans: 'Zero by definition' }],
            flashcards: [{ front: 'Hess\'s Law', back: 'Total enthalpy change is same regardless of path — enthalpy is a state function' }],
        },
        'Solutions': {
            concepts: ['Types of solutions: solid, liquid, gaseous', 'Raoult\'s law: P = x·P°', 'Colligative properties: ΔTb, ΔTf, π', 'Henry\'s law for gas dissolution', 'Van\'t Hoff factor i for electrolytes'],
            formulas: ['Molality = moles solute / kg solvent', 'ΔTb = iKbm', 'ΔTf = iKfm', 'π = iCRT', 'Raoult: P_A = x_A·P_A°'],
            solvedExample: { q: 'Boiling point elevation: 0.5m glucose in water, Kb=0.52?', a: 'ΔTb = 0.52×0.5 = 0.26°C, bp = 100.26°C' },
            practiceQs: [{ q: 'Which is NOT a colligative property?', opts: ['Viscosity', 'Osmotic pressure', 'Boiling point elevation', 'Freezing point depression'], ans: 0 }, { q: 'Van\'t Hoff factor for NaCl?', opts: ['2', '1', '3', '0.5'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Osmotic pressure of 0.1M glucose at 300K?', ans: 'π = CRT = 0.1×0.0821×300 = 2.463 atm' }],
            flashcards: [{ front: 'Ideal solution', back: 'Obeys Raoult\'s law at all concentrations. ΔH_mix = 0, ΔV_mix = 0' }],
        },
        'Equilibrium': {
            concepts: ['Le Chatelier\'s principle', 'Kp and Kc relationship', 'Ionic equilibrium: acids, bases, buffers', 'Common ion effect', 'Solubility product Ksp'],
            formulas: ['Kp = Kc(RT)^Δn', 'pH = −log[H⁺]', 'pOH = −log[OH⁻]', 'pH + pOH = 14', 'Henderson: pH = pKa + log([A⁻]/[HA])'],
            solvedExample: { q: 'pH of 0.01M HCl?', a: 'pH = −log(0.01) = 2' },
            practiceQs: [{ q: 'Buffer solution contains?', opts: ['Weak acid + conjugate base', 'Strong acid + strong base', 'Two strong acids', 'Pure water'], ans: 0 }, { q: 'If Ksp of AgCl = 10⁻¹⁰, solubility?', opts: ['10⁻⁵ M', '10⁻¹⁰ M', '10⁻² M', '10⁻⁸ M'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'pH of 10⁻⁸ M HCl?', ans: '6.98 (not 8, consider water autoionization)' }],
            flashcards: [{ front: 'Le Chatelier\'s principle', back: 'System at equilibrium shifts to counteract any imposed change (concentration, pressure, temperature)' }],
        },
        'Redox Reactions': {
            concepts: ['Oxidation: loss of electrons, increase in oxidation state', 'Reduction: gain of electrons, decrease in oxidation state', 'Balancing redox by half-reaction method', 'Oxidation number rules', 'Electrochemical series'],
            formulas: ['Oxidation number of free element = 0', 'Sum of ON in compound = 0', 'Sum of ON in ion = charge'],
            solvedExample: { q: 'Assign oxidation states in KMnO₄.', a: 'K=+1, O=−2, so Mn + 1 + 4(−2) = 0 → Mn = +7' },
            practiceQs: [{ q: 'In Fe₂O₃ + 3CO → 2Fe + 3CO₂, oxidizing agent?', opts: ['Fe₂O₃', 'CO', 'Fe', 'CO₂'], ans: 0 }, { q: 'Oxidation state of S in H₂SO₄?', opts: ['+6', '+4', '−2', '0'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Which can act as both oxidizing and reducing agent?', ans: 'H₂O₂' }],
            flashcards: [{ front: 'Disproportionation', back: 'Same element is simultaneously oxidized and reduced. Example: 2H₂O₂ → 2H₂O + O₂' }],
        },
        'Electrochemistry': {
            concepts: ['Electrode potential and EMF', 'Nernst equation', 'Faraday\'s laws of electrolysis', 'Galvanic vs electrolytic cells', 'Conductivity and molar conductivity'],
            formulas: ['E_cell = E°_cathode − E°_anode', 'Nernst: E = E° − (RT/nF)lnQ', '1 Faraday = 96485 C/mol', 'Λm = κ/c', 'Kohlrausch: Λ°m = Σλ°'],
            solvedExample: { q: 'EMF of Zn|Zn²⁺||Cu²⁺|Cu cell? E°(Zn)=−0.76V, E°(Cu)=+0.34V', a: 'E = 0.34−(−0.76) = 1.10 V' },
            practiceQs: [{ q: 'At SHE, potential is?', opts: ['0.00 V', '1.00 V', '−0.76 V', '0.34 V'], ans: 0 }, { q: 'In electrolysis, cathode is?', opts: ['Negative', 'Positive', 'Neutral', 'Varies'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Mass deposited by 2F of charge on Cu²⁺?', ans: '63.5 g (1 mole of Cu)' }],
            flashcards: [{ front: 'Standard Hydrogen Electrode', back: 'Reference electrode: E° = 0.00 V at 298K, 1atm H₂, 1M H⁺' }],
        },
        'Chemical Kinetics': {
            concepts: ['Rate = change in concentration / time', 'Order from rate law (experimentally determined)', 'Zero, first, second order kinetics', 'Half-life depends on order', 'Arrhenius equation: k = Ae⁻ᴱᵃ/ᴿᵀ'],
            formulas: ['First order: t½ = 0.693/k', 'First order: ln[A] = ln[A₀] − kt', 'Arrhenius: ln(k₂/k₁) = Ea/R(1/T₁ − 1/T₂)', 'Zero order: t½ = [A₀]/2k'],
            solvedExample: { q: 'First order reaction, k = 0.01 s⁻¹. Find half-life.', a: 't½ = 0.693/0.01 = 69.3 s' },
            practiceQs: [{ q: 'Unit of first order rate constant?', opts: ['s⁻¹', 'mol/L/s', 'L/mol/s', 'L²/mol²/s'], ans: 0 }, { q: 'Activation energy can be found from?', opts: ['Arrhenius plot (lnk vs 1/T)', 'Rate vs concentration', 'pH measurement', 'Conductance'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'For a first order reaction, time for 99% completion?', ans: '6.9 × t½' }],
            flashcards: [{ front: 'Activation energy (Ea)', back: 'Minimum energy for reactant molecules to undergo reaction. Catalyst lowers Ea.' }],
        },
        'Classification of Elements and Periodicity': {
            concepts: ['Modern periodic law: properties are periodic function of atomic number', 'Blocks: s, p, d, f', 'Periodic trends: atomic radius, IE, EA, EN', 'Metallic character decreases across period', 'Diagonal relationship'],
            formulas: ['IE₁ < IE₂ < IE₃ (successive)', 'EN (Pauling scale): F=4.0 highest', 'Atomic radius: decreases across period, increases down group'],
            solvedExample: { q: 'Arrange Na, Mg, Al, Si in order of increasing IE.', a: 'Na < Al < Mg < Si (Al lower than Mg due to 3p vs 3s)' },
            practiceQs: [{ q: 'Most electronegative element?', opts: ['F', 'O', 'Cl', 'N'], ans: 0 }, { q: 'Which has largest atomic radius?', opts: ['Cs', 'Li', 'Na', 'K'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Exception in IE trend: N vs O?', ans: 'IE of N > O due to half-filled 2p stability' }],
            flashcards: [{ front: 'Electron affinity trend', back: 'Generally increases across period (Cl has highest EA, not F due to small size repulsion)' }],
        },
        'p-Block Elements': {
            concepts: ['Group 13-18 elements', 'Inert pair effect in heavier elements', 'Allotropy of carbon, sulfur, phosphorus', 'Oxoacids of P, S, N, Cl', 'Noble gas compounds (XeF₂, XeF₄, XeF₆)'],
            formulas: ['Boron: electron deficient, forms back bonds', 'Carbon: catenation ability', 'Nitrogen: forms multiple bonds easily'],
            solvedExample: { q: 'Why does N₂ have a triple bond while P₂ doesn\'t form easily?', a: 'N is small, forms effective pπ-pπ overlap for triple bond. P is larger, prefers single bonds.' },
            practiceQs: [{ q: 'Strongest oxidizing agent among halogens?', opts: ['F₂', 'Cl₂', 'Br₂', 'I₂'], ans: 0 }, { q: 'Which noble gas forms maximum compounds?', opts: ['Xe', 'Kr', 'Ar', 'He'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Structure of PCl₅ in solid state?', ans: '[PCl₄]⁺[PCl₆]⁻ (ionic)' }],
            flashcards: [{ front: 'Inert pair effect', back: 'Heavier p-block elements show +2 state preference (e.g., Pb²⁺ > Pb⁴⁺) due to poor shielding of ns²' }],
        },
        'd- and f-Block Elements': {
            concepts: ['Transition metals: partially filled d orbitals', 'Variable oxidation states', 'Colored compounds due to d-d transitions', 'Catalytic activity', 'Lanthanide contraction'],
            formulas: ['Magnetic moment μ = √(n(n+2)) BM', 'Common ON: Mn(+2,+4,+7), Cr(+3,+6), Fe(+2,+3)'],
            solvedExample: { q: 'Calculate magnetic moment of Fe²⁺ (3d⁶).', a: '4 unpaired electrons → μ = √(4×6) = √24 = 4.9 BM' },
            practiceQs: [{ q: 'Which transition metal shows maximum oxidation states?', opts: ['Mn', 'Fe', 'Cu', 'Zn'], ans: 0 }, { q: 'Why are transition metal compounds colored?', opts: ['d-d transitions', 'High melting point', 'Metallic bonding', 'Large size'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Lanthanide contraction causes?', ans: 'Similar radii of 4d and 5d series elements (Zr≈Hf)' }],
            flashcards: [{ front: 'Lanthanide contraction', back: 'Gradual decrease in size across lanthanides due to poor shielding by 4f electrons' }],
        },
        'Coordination Compounds': {
            concepts: ['Werner\'s theory: primary and secondary valence', 'IUPAC nomenclature of complexes', 'Crystal field theory (CFT)', 'Isomerism: geometrical, optical, linkage', 'Spectrochemical series'],
            formulas: ['CFSE in octahedral: Δ₀ splitting', 't₂g and eg in octahedral', 'EAN = Z − ON + 2×CN'],
            solvedExample: { q: 'Name [Co(NH₃)₆]Cl₃.', a: 'Hexaamminecobalt(III) chloride' },
            practiceQs: [{ q: 'Coordination number in [Fe(CN)₆]⁴⁻?', opts: ['6', '4', '2', '8'], ans: 0 }, { q: '[Ni(CO)₄] is?', opts: ['Tetrahedral', 'Square planar', 'Octahedral', 'Linear'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Which has highest CFSE?', ans: '[Co(CN)₆]³⁻ (strong field, low spin d⁶)' }],
            flashcards: [{ front: 'Spectrochemical series', back: 'I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < NO₂⁻ < CN⁻ < CO (increasing Δ)' }],
        },
        'Purification and Characterisation of Organic Compounds': {
            concepts: ['Distillation: simple, fractional, steam, vacuum', 'Crystallization for solid purification', 'Chromatography: column, TLC, paper', 'Qualitative analysis: Lassaigne test for N, S, halogens', 'Quantitative: estimation of C, H, N, halogens'],
            formulas: ['% C = (12×mass CO₂)/(44×mass sample)×100', '% H = (2×mass H₂O)/(18×mass sample)×100', '% N (Dumas) = 28×vol N₂/(22400×mass)×100'],
            solvedExample: { q: '0.30g organic compound gives 0.88g CO₂ and 0.18g H₂O. Find %C and %H.', a: '%C = 12×0.88/(44×0.30)×100 = 80%, %H = 2×0.18/(18×0.30)×100 = 6.67%' },
            practiceQs: [{ q: 'Lassaigne test detects?', opts: ['N, S, halogens', 'C and H only', 'Metals', 'Double bonds'], ans: 0 }, { q: 'Steam distillation is used for?', opts: ['Immiscible, volatile organic liquids', 'Gases', 'Salts', 'Non-volatile solids'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Rf value in TLC depends on?', ans: 'Polarity of compound and solvent system' }],
            flashcards: [{ front: 'Chromatography principle', back: 'Differential adsorption/partition of components between stationary and mobile phase' }],
        },
        'Basic Principles of Organic Chemistry': {
            concepts: ['IUPAC nomenclature rules', 'Hybridization: sp³, sp², sp', 'Inductive, mesomeric, hyperconjugation effects', 'Electrophiles and nucleophiles', 'Reaction intermediates: carbocation, carbanion, free radical'],
            formulas: ['Degree of unsaturation = (2C+2+N−H−X)/2', 'Stability: 3°>2°>1° carbocation', 'Acidity order from −I and +R effects'],
            solvedExample: { q: 'Degree of unsaturation of C₆H₆ (benzene)?', a: 'DoU = (2×6+2−6)/2 = 4 (3 double bonds + 1 ring)' },
            practiceQs: [{ q: 'Strongest nucleophile in polar aprotic solvent?', opts: ['I⁻', 'F⁻', 'Cl⁻', 'Br⁻'], ans: 0 }, { q: 'Carbocation stability: CH₃⁺ vs (CH₃)₃C⁺?', opts: ['(CH₃)₃C⁺ more stable', 'CH₃⁺ more stable', 'Equal', 'Cannot compare'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Hyperconjugation involves?', ans: 'σ-bond electrons delocalizing into vacant p-orbital' }],
            flashcards: [{ front: 'SN1 vs SN2', back: 'SN1: 2-step, carbocation, 3° preferred. SN2: 1-step, backside attack, 1° preferred' }],
        },
        'Hydrocarbons': {
            concepts: ['Alkanes: saturated, sp³, substitution reactions', 'Alkenes: one C=C, sp², addition reactions', 'Alkynes: one C≡C, sp, addition reactions', 'Aromatic: benzene, Hückel (4n+2)π rule', 'Markovnikov and anti-Markovnikov addition'],
            formulas: ['CnH₂n+₂ (alkanes)', 'CnH₂n (alkenes/cycloalkanes)', 'CnH₂n−₂ (alkynes)'],
            solvedExample: { q: 'Product of HBr addition to propene (Markovnikov)?', a: '2-bromopropane (Br on more substituted C)' },
            practiceQs: [{ q: 'Benzene undergoes?', opts: ['Electrophilic substitution', 'Addition easily', 'Elimination', 'Nucleophilic substitution'], ans: 0 }, { q: 'Ozonolysis of ethene gives?', opts: ['Formaldehyde', 'Acetone', 'Acetic acid', 'Ethanol'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Anti-Markovnikov addition occurs with?', ans: 'HBr in presence of peroxide (Kharasch effect)' }],
            flashcards: [{ front: 'Hückel\'s rule', back: 'Aromatic if planar, cyclic, conjugated, and has (4n+2)π electrons' }],
        },
        'Organic Compounds Containing Halogens': {
            concepts: ['Preparation from alcohols, alkenes, arenes', 'SN1 and SN2 mechanisms', 'Elimination: E1, E2', 'Grignard reagent: RMgX', 'Polyhalogen compounds: CHCl₃, CCl₄, freons'],
            formulas: ['SN2 rate = k[substrate][nucleophile]', 'SN1 rate = k[substrate]', 'Reactivity: R-I > R-Br > R-Cl > R-F'],
            solvedExample: { q: 'Arrange CH₃Cl, CH₃Br, CH₃I in order of SN2 reactivity.', a: 'CH₃I > CH₃Br > CH₃Cl (better leaving group)' },
            practiceQs: [{ q: 'Grignard reagent reacts with CO₂ to give?', opts: ['Carboxylic acid', 'Aldehyde', 'Ketone', 'Alcohol'], ans: 0 }, { q: 'Inversion of configuration occurs in?', opts: ['SN2', 'SN1', 'E1', 'E2'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Finkelstein reaction converts?', ans: 'R-Cl/R-Br to R-I using NaI in acetone' }],
            flashcards: [{ front: 'Walden inversion', back: 'Complete inversion of stereochemistry at chiral center during SN2 reaction' }],
        },
        'Organic Compounds Containing Oxygen': {
            concepts: ['Alcohols, phenols, ethers — nomenclature and reactions', 'Aldehydes and ketones — nucleophilic addition', 'Carboxylic acids — acidity and derivatives', 'Cannizzaro, Aldol, cross-Aldol reactions', 'Ester formation and saponification'],
            formulas: ['Acidity: RCOOH > PhOH > ROH > H₂O', 'Lucas test: 3° > 2° > 1° alcohol reactivity'],
            solvedExample: { q: 'Product of Aldol condensation of acetaldehyde?', a: '3-hydroxybutanal (β-hydroxy aldehyde), then crotonaldehyde on heating' },
            practiceQs: [{ q: 'Tollens test is positive for?', opts: ['Aldehydes', 'Ketones', 'Alcohols', 'Ethers'], ans: 0 }, { q: 'Which cannot reduce Fehling solution?', opts: ['Benzaldehyde', 'Formaldehyde', 'Acetaldehyde', 'Glucose'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'Williamson synthesis is used to prepare?', ans: 'Ethers (R-O-R\')' }],
            flashcards: [{ front: 'Cannizzaro reaction', back: 'Non-enolizable aldehyde + strong base → one molecule oxidized to acid, one reduced to alcohol' }],
        },
        'Organic Compounds Containing Nitrogen': {
            concepts: ['Amines: classification (1°, 2°, 3°), basicity', 'Diazonium salts: preparation and reactions', 'Carbylamine reaction for 1° amines', 'Hofmann bromamide reaction', 'Sandmeyer reaction for aryl halides'],
            formulas: ['Basicity: aliphatic amines > NH₃ > aromatic amines', 'In gas phase: 3° > 2° > 1° > NH₃', 'In aqueous: 2° > 1° > 3° > NH₃'],
            solvedExample: { q: 'Order of basicity: aniline, methylamine, dimethylamine?', a: 'Dimethylamine > methylamine > aniline (resonance reduces aniline basicity)' },
            practiceQs: [{ q: 'Carbylamine test is for?', opts: ['Primary amines', 'Secondary amines', 'Tertiary amines', 'All amines'], ans: 0 }, { q: 'Diazonium salt is stable only at?', opts: ['0-5°C', '100°C', 'Room temp', '50°C'], ans: 0 }],
            pyqs: [{ year: 'JEE 2023', q: 'Gabriel phthalimide synthesis gives?', ans: 'Primary amines only' }],
            flashcards: [{ front: 'Hinsberg test', back: 'Distinguishes 1°, 2°, 3° amines using benzenesulfonyl chloride' }],
        },
        'Biomolecules': {
            concepts: ['Carbohydrates: mono, di, polysaccharides', 'Amino acids: 20 standard, peptide bond', 'Proteins: primary to quaternary structure', 'Nucleic acids: DNA and RNA', 'Enzymes: biological catalysts, lock-and-key model'],
            formulas: ['Peptide bond: -CO-NH- (amide linkage)', 'Wöhler synthesis: NH₄OCN → urea (first organic from inorganic)'],
            solvedExample: { q: 'How many peptide bonds in a tripeptide?', a: '2 peptide bonds (n−1 bonds for n amino acids)' },
            practiceQs: [{ q: 'Glucose is an example of?', opts: ['Aldohexose', 'Ketohexose', 'Aldopentose', 'Ketopentose'], ans: 0 }, { q: 'DNA contains which sugar?', opts: ['Deoxyribose', 'Ribose', 'Glucose', 'Fructose'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Denaturation of protein affects?', ans: 'Secondary and higher structures (not primary/peptide bonds)' }],
            flashcards: [{ front: 'Essential amino acids', back: 'Cannot be synthesized by body, must come from diet. E.g., valine, leucine, lysine' }],
        },
        'Principles Related to Practical Chemistry': {
            concepts: ['Salt analysis: cation and anion detection', 'Preparation of standard solutions', 'Titration: acid-base, permanganometry', 'Qualitative tests for functional groups', 'Chromatography and distillation in lab'],
            formulas: ['Normality = Equivalents/L', 'N₁V₁ = N₂V₂ (titration)', 'Molarity × n-factor = Normality'],
            solvedExample: { q: '25mL of 0.1M NaOH neutralizes what volume of 0.05M HCl?', a: 'N₁V₁=N₂V₂: 0.1×25 = 0.05×V₂, V₂ = 50 mL' },
            practiceQs: [{ q: 'Indicator for strong acid vs weak base titration?', opts: ['Methyl orange', 'Phenolphthalein', 'Litmus', 'Universal'], ans: 0 }, { q: 'Flame test: Na gives?', opts: ['Golden yellow', 'Brick red', 'Green', 'Violet'], ans: 0 }],
            pyqs: [{ year: 'JEE 2022', q: 'KMnO₄ is self-indicator because?', ans: 'Pink/purple color disappears at endpoint; excess gives pink color' }],
            flashcards: [{ front: 'End point vs equivalence point', back: 'End point: indicator changes color. Equivalence point: stoichiometric amounts reacted. Ideally they match.' }],
        },
    },
    // ═══════════════════════════════════════════════════════════════
    // BIOLOGY
    // ═══════════════════════════════════════════════════════════════
    Biology: {
        'Diversity in Living World': {
            concepts: ['Taxonomy: classification of living organisms', 'Five kingdom classification: Monera, Protista, Fungi, Plantae, Animalia', 'Binomial nomenclature (Linnaeus)', 'Taxonomic hierarchy: Kingdom→Phylum→Class→Order→Family→Genus→Species', 'Biodiversity and conservation'],
            formulas: ['Taxonomic key identifiers for major phyla', 'Classification mnemonics: King Philip Came Over For Good Spaghetti'],
            solvedExample: { q: 'Classify humans using binomial nomenclature.', a: 'Homo sapiens (Genus: Homo, Species: sapiens)' },
            practiceQs: [{ q: 'Smallest unit of classification?', opts: ['Species', 'Genus', 'Family', 'Order'], ans: 0 }, { q: 'Fungi cell wall is made of?', opts: ['Chitin', 'Cellulose', 'Peptidoglycan', 'Silica'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Which kingdom includes both autotrophs and heterotrophs?', ans: 'Protista' }],
            flashcards: [{ front: 'Binomial nomenclature', back: 'Two-part Latin name: Genus (capitalized) + species (lowercase), italicized. E.g., Homo sapiens' }],
        },
        'Structural Organisation in Animals and Plants': {
            concepts: ['Plant tissues: meristematic and permanent', 'Animal tissues: epithelial, connective, muscular, nervous', 'Morphology of flowering plants', 'Anatomy of root, stem, leaf', 'Organ systems in animals: digestive, respiratory, circulatory'],
            formulas: ['Tissue types and their locations/functions'],
            solvedExample: { q: 'Differentiate between xylem and phloem.', a: 'Xylem: transports water upward, dead cells. Phloem: transports food bidirectionally, living cells.' },
            practiceQs: [{ q: 'Meristematic tissue is responsible for?', opts: ['Growth', 'Protection', 'Transport', 'Storage'], ans: 0 }, { q: 'Cardiac muscle is?', opts: ['Involuntary and striated', 'Voluntary and striated', 'Involuntary and smooth', 'Voluntary and smooth'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'Collenchyma differs from sclerenchyma in?', ans: 'Collenchyma has pectin thickening (living); sclerenchyma has lignin (dead)' }],
            flashcards: [{ front: 'Types of vascular bundles', back: 'Open (with cambium, dicots) and closed (without cambium, monocots)' }],
        },
        'Cell Structure and Function': {
            concepts: ['Cell theory: Schleiden and Schwann', 'Prokaryotic vs eukaryotic cells', 'Cell organelles: nucleus, mitochondria, ER, Golgi, lysosomes', 'Cell division: mitosis and meiosis', 'Cell cycle: G1, S, G2, M phases'],
            formulas: ['Mitosis: 2n → 2n (identical)', 'Meiosis: 2n → n (reduces to half)', 'S phase: DNA replication'],
            solvedExample: { q: 'How many chromosomes after mitosis if parent has 46?', a: '46 chromosomes in each daughter cell (identical to parent)' },
            practiceQs: [{ q: 'Powerhouse of the cell?', opts: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi'], ans: 0 }, { q: 'Crossing over occurs in?', opts: ['Meiosis I prophase', 'Mitosis', 'Meiosis II', 'S phase'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Function of rough ER?', ans: 'Protein synthesis (ribosomes on surface)' }],
            flashcards: [{ front: 'Difference: mitosis vs meiosis', back: 'Mitosis: 1 division, 2 identical cells. Meiosis: 2 divisions, 4 genetically different cells (half chromosomes)' }],
        },
        'Plant Physiology': {
            concepts: ['Photosynthesis: light and dark reactions', 'Transpiration: factors and significance', 'Mineral nutrition: essential elements', 'Plant growth regulators: auxin, gibberellin, cytokinin', 'Nitrogen cycle and nitrogen fixation'],
            formulas: ['6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', 'C3 (Calvin) vs C4 (Hatch-Slack) pathway', 'Transpiration pull theory'],
            solvedExample: { q: 'Where does light reaction occur?', a: 'Thylakoid membranes of chloroplast (grana)' },
            practiceQs: [{ q: 'CO₂ fixation in C4 plants first produces?', opts: ['OAA (4-carbon)', 'PGA (3-carbon)', 'Glucose', 'RuBP'], ans: 0 }, { q: 'Nitrogen fixation is done by?', opts: ['Rhizobium', 'E. coli', 'Yeast', 'Amoeba'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Kranz anatomy is characteristic of?', ans: 'C4 plants (bundle sheath cells around vascular bundles)' }],
            flashcards: [{ front: 'Photorespiration', back: 'RuBisCO fixes O₂ instead of CO₂. Wastes energy. Absent in C4 plants due to CO₂ concentration mechanism.' }],
        },
        'Human Physiology': {
            concepts: ['Digestive system: mechanical and chemical digestion', 'Respiratory system: alveolar gas exchange', 'Circulatory system: double circulation, cardiac cycle', 'Excretory system: nephron structure and function', 'Nervous system: CNS and PNS'],
            formulas: ['Cardiac output = stroke volume × heart rate', 'GFR ≈ 125 mL/min', 'Tidal volume ≈ 500 mL', 'Vital capacity = TV + IRV + ERV'],
            solvedExample: { q: 'If heart rate is 72 bpm and stroke volume is 70 mL, find cardiac output.', a: 'CO = 72 × 70 = 5040 mL/min ≈ 5 L/min' },
            practiceQs: [{ q: 'Pacemaker of heart?', opts: ['SA node', 'AV node', 'Bundle of His', 'Purkinje fibers'], ans: 0 }, { q: 'Functional unit of kidney?', opts: ['Nephron', 'Neuron', 'Glomerulus', 'Loop of Henle'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'Oxygen is transported in blood mainly as?', ans: 'Oxyhemoglobin (98.5%)' }],
            flashcards: [{ front: 'SA node', back: 'Sinoatrial node — the natural pacemaker of the heart, located in right atrium' }],
        },
        'Reproduction': {
            concepts: ['Asexual vs sexual reproduction', 'Flower structure: stamen (male) and pistil (female)', 'Gametogenesis: spermatogenesis and oogenesis', 'Fertilization and embryo development', 'Menstrual cycle: 28-day cycle'],
            formulas: ['Menstrual phases: menstrual (1-5), follicular (6-13), ovulation (14), luteal (15-28)', 'Double fertilization in plants: one sperm + egg → zygote, one sperm + polar nuclei → endosperm'],
            solvedExample: { q: 'What is double fertilization?', a: 'One sperm fuses with egg (2n zygote), another with 2 polar nuclei (3n endosperm). Unique to angiosperms.' },
            practiceQs: [{ q: 'Corpus luteum secretes?', opts: ['Progesterone', 'Estrogen', 'FSH', 'LH'], ans: 0 }, { q: 'Endosperm is?', opts: ['Triploid (3n)', 'Diploid (2n)', 'Haploid (n)', 'Tetraploid (4n)'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'IVF stands for?', ans: 'In Vitro Fertilization (test tube baby technique)' }],
            flashcards: [{ front: 'Corpus luteum', back: 'Formed from ruptured follicle after ovulation. Secretes progesterone to maintain uterine lining.' }],
        },
        'Genetics and Evolution': {
            concepts: ['Mendel\'s laws: segregation and independent assortment', 'DNA structure: double helix, A-T, G-C', 'Central dogma: DNA→RNA→Protein', 'Mutations: point, frameshift, chromosomal', 'Evolution: natural selection, genetic drift, Hardy-Weinberg'],
            formulas: ['Monohybrid: 3:1 phenotypic ratio', 'Dihybrid: 9:3:3:1', 'Test cross: used to determine genotype', 'Chargaff: A=T, G=C'],
            solvedExample: { q: 'Cross Tt × Tt. Find phenotypic ratio.', a: 'TT:Tt:tt = 1:2:1, Phenotype: 3 tall : 1 short' },
            practiceQs: [{ q: 'DNA replication is?', opts: ['Semi-conservative', 'Conservative', 'Dispersive', 'Random'], ans: 0 }, { q: 'Codon AUG codes for?', opts: ['Methionine (start)', 'Stop', 'Alanine', 'Glycine'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'Chargaff\'s rule states?', ans: 'A=T and G=C in DNA' }],
            flashcards: [{ front: 'Codominance', back: 'Both alleles expressed equally. Example: AB blood group (IᴬIᴮ)' }],
        },
        'Biology and Human Welfare': {
            concepts: ['Human health and diseases', 'Immunity: innate and adaptive', 'Vaccines and immunization', 'Cancer: types and causes', 'Drugs and alcohol abuse'],
            formulas: ['Types of immunity: active (natural/artificial), passive (natural/artificial)', 'Antibody structure: Y-shaped, 2 heavy + 2 light chains'],
            solvedExample: { q: 'Differentiate active and passive immunity.', a: 'Active: body makes own antibodies (slow, long-lasting). Passive: preformed antibodies given (immediate, short-lived).' },
            practiceQs: [{ q: 'AIDS is caused by?', opts: ['HIV (retrovirus)', 'Bacteria', 'Fungus', 'Prion'], ans: 0 }, { q: 'First line of defense?', opts: ['Skin and mucous membranes', 'Antibodies', 'T-cells', 'B-cells'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'Which immunoglobulin is found in colostrum?', ans: 'IgA' }],
            flashcards: [{ front: 'Interferon', back: 'Proteins released by virus-infected cells that protect neighboring cells from viral infection' }],
        },
        'Biotechnology and Its Applications': {
            concepts: ['Recombinant DNA technology', 'PCR: Polymerase Chain Reaction', 'Restriction enzymes: molecular scissors', 'Vectors: plasmids, bacteriophages', 'Applications: insulin, Bt crops, gene therapy'],
            formulas: ['PCR steps: Denaturation (94°C) → Annealing (55°C) → Extension (72°C)', 'After n cycles: 2ⁿ copies'],
            solvedExample: { q: 'After 20 PCR cycles, how many copies from 1 DNA molecule?', a: '2²⁰ = 1,048,576 copies (approximately 1 million)' },
            practiceQs: [{ q: 'Restriction enzymes cut DNA at?', opts: ['Palindromic sequences', 'Any sequence', 'Promoter region', 'Telomeres'], ans: 0 }, { q: 'Bt in Bt cotton stands for?', opts: ['Bacillus thuringiensis', 'Biotechnology', 'Beta toxin', 'Bacterial transfer'], ans: 0 }],
            pyqs: [{ year: 'NEET 2023', q: 'First genetically engineered product approved for human use?', ans: 'Human insulin (Humulin)' }],
            flashcards: [{ front: 'Palindromic sequences', back: 'DNA sequences that read same on both strands 5\'→3\'. E.g., GAATTC (EcoRI site)' }],
        },
        'Ecology and Environment': {
            concepts: ['Ecosystem: biotic + abiotic components', 'Food chain, food web, trophic levels', 'Energy flow: 10% rule', 'Ecological pyramids: number, biomass, energy', 'Biogeochemical cycles: carbon, nitrogen, phosphorus'],
            formulas: ['10% energy transfer law (Lindeman)', 'Primary productivity = GPP; NPP = GPP − R', 'Population growth: dN/dt = rN (exponential) or rN(K−N)/K (logistic)'],
            solvedExample: { q: 'If producers fix 10000 J, how much energy reaches tertiary consumers?', a: '10000 → 1000 (primary) → 100 (secondary) → 10 J (tertiary)' },
            practiceQs: [{ q: 'Pyramid of energy is always?', opts: ['Upright', 'Inverted', 'Spindle-shaped', 'Flat'], ans: 0 }, { q: 'Biodiversity hotspot requires?', opts: ['High endemism + habitat loss', 'Only large area', 'Cold climate', 'No human activity'], ans: 0 }],
            pyqs: [{ year: 'NEET 2022', q: 'r-selected species have?', ans: 'High reproductive rate, short lifespan, small body size' }],
            flashcards: [{ front: 'Ecological succession', back: 'Gradual replacement of one community by another. Primary (bare rock) vs secondary (disturbed area).' }],
        },
    },
};
